#include <linux/ioctl.h>

#define MEMCACHE_IOC_MAGIC  		'm'
#define MEMCACHE_IOCCRESET	    	_IO(MEMCACHE_IOC_MAGIC, 0)
#define MEMCACHE_IOCGETCACHE    	_IOR(MEMCACHE_IOC_MAGIC, 1, int)
#define MEMCACHE_IOCSETCACHE 		_IOW(MEMCACHE_IOC_MAGIC, 2, int)
#define MEMCACHE_IOCTRUNC 		_IO(MEMCACHE_IOC_MAGIC, 3)
#define MEMCACHE_IOCQBUFSIZE 		_IO(MEMCACHE_IOC_MAGIC, 4)
#define MEMCACHE_IOCGTESTCACHE 		_IOR(MEMCACHE_IOC_MAGIC, 5, int)
#define MEMCACHE_IOC_MAXNR 		5

